service: codecheck-restful-api

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

functions:
  create:
    handler: source/route/create.post
    events:
      - http:
          path: recipes
          method: post
  getList:
    handler: source/route/getList.get
    events:
      - http:
          path: recipes
          method: get
  get:
    handler: source/route/get.get
    events:
      - http:
          path: recipes/{id}
          method: get
  update:
    handler: source/route/update.patch
    events:
      - http:
          path: recipes/{id}
          method: patch
  remove:
    handler: source/route/remove.delete
    events:
      - http:
          path: recipes/{id}
          method: delete
